### ISSUE TITLE
[bug] pyLDAPmonitor trying to authenticate even when --password is set

### ISSUE THREAD

**Issue by thibon** [p0dalirius/LDAPmonitor#16]
Hey there,

First, thanks for the tool, always helpful to prevent mistakes!

When I tried to use it today, I found a weird behavior: script is trying to authenticate with hashes when I pass the option --password.
I managed to solve that by forcing auth_nt_hash to None instead of empty string before sending it to init_ldap_session(). Maybe a change in sectools.windows.ldap ?

Context note: Working in exegol, first time I see this, no problems before but haven't used LDAPMonitor since 3/4 months

**Comment by p0dalirius** [comment]
Hi,

Thank you for your kind words!
I did a change in `sectools.windows.ldap` that broke authentication, sorry for this. This is fixed in `sectools>=1.4.3`

Please reopen the issue if the issue persists.

Best regards,
