### ISSUE TITLE
[enhancement] Missing constructed LDAP attributes

### ISSUE THREAD

**Issue by Hackndo** [p0dalirius/LDAPmonitor#24]
Some constructed attributes are missing. For example [msDS-ResultantPSO](https://learn.microsoft.com/fr-fr/windows/win32/adschema/a-msds-resultantpso), [msDS-User-Account-Control-Computed](https://learn.microsoft.com/fr-fr/windows/win32/adschema/a-msds-user-account-control-computed), ...
My quick fix was to query these attributes explicitly but there may be a cleaner way.

```python
ALL_ATTR = [
   ldap3.ALL_ATTRIBUTES,
   ldap3.ALL_OPERATIONAL_ATTRIBUTES,
   'allowedAttributes',
   'allowedAttributesEffective',
   'allowedChildClasses',
   'allowedChildClassesEffective',
   'aNR',
   'attributeTypes',
   'canonicalName',
   'createTimeStamp',
   'dITContentRules',
   'entryTTL',
   'extendedAttributeInfo',
   'extendedClassInfo',
   'fromEntry',
   'modifyTimeStamp',
   'msDS-Auxiliary-Classes',
   'msDS-Approx-Immed-Subordinates',
   'msDS-isGC',
   'msDS-isRODC',
   'msDS-KeyVersionNumber',
   'msDS-LocalEffectiveDeletionTime',
   'msDS-LocalEffectiveRecycleTime',
   'msDS-ResultantPSO',
   'msDS-SiteName',
   'msDS-TopQuotaUsage',
   'msDS-PrincipalName',
   'msDS-QuotaEffective',
   'msDS-QuotaUsed',
   'msDS-User-Account-Control-Computed',
   'msDS-UserPasswordExpiryTimeComputed',
   'msDS-IsUserCachableAtRodc',
   'msDS-RevealedListBL',
   'objectClasses',
   'parentGUID',
   'possibleInferiors',
   'primaryGroupToken',
   'sDRightsEffective',
   'structuralObjectClass',
   'msDS-parentdistname'
 ]
```

**Comment by p0dalirius** [comment]
Hi @Hackndo!

Thank your for the suggestion, do you know how to find the list of attributes that are hidden? In the MS docs or other?

I am trying to find a difference between hidden `anr` and visible `description` attributes:

### Attribute `description`
![image](https://github.com/p0dalirius/LDAPmonitor/assets/79218792/a745fb47-3870-4378-a043-5b3fd5050f51)

### Attribute `anr`
![image](https://github.com/p0dalirius/LDAPmonitor/assets/79218792/5834e0dd-a958-44b9-8e43-2139dc626b9e)


Best regards,

**Comment by p0dalirius** [comment]
I have implemented it, on a fresh Windows server 2019 it will query the following attributes:

```python
[
'*', 
'aNR', 
'allowedAttributes', 
'allowedAttributesEffective', 
'allowedChildClasses', 
'allowedChildClassesEffective', 
'attributeTypes', 
'canonicalName', 
'createTimeStamp', 
'dITContentRules', 
'entryTTL', 
'extendedAttributeInfo', 
'extendedClassInfo', 
'fromEntry', 
'modifyTimeStamp', 
'msDS-Approx-Immed-Subordinates', 
'msDS-Auxiliary-Classes',
'msDS-IsUserCachableAtRodc', 
'msDS-KeyVersionNumber', 
'msDS-LocalEffectiveDeletionTime', 
'msDS-LocalEffectiveRecycleTime', 
'msDS-ManagedPassword', 
'msDS-NCReplCursors', 
'msDS-NCReplInboundNeighbors',
'msDS-NCReplOutboundNeighbors', 
'msDS-PrincipalName', 
'msDS-QuotaEffective', 
'msDS-QuotaUsed', 
'msDS-ReplAttributeMetaData', 
'msDS-ReplValueMetaData', 
'msDS-ReplValueMetaDataExt', 
'msDS-ResultantPSO', 
'msDS-RevealedList', 
'msDS-RevealedListBL', 
'msDS-SiteName', 
'msDS-TopQuotaUsage',
'msDS-User-Account-Control-Computed', 
'msDS-UserPasswordExpiryTimeComputed', 
'msDS-isGC', 
'msDS-isRODC', 
'msDS-parentdistname',
'msds-memberOfTransitive', 
'msds-memberTransitive', 
'msds-tokenGroupNames', 
'msds-tokenGroupNamesGlobalAndUniversal', 
'msds-tokenGroupNamesNoGCAcceptable', 
'objectClasses', 
'parentGUID', 
'possibleInferiors', 
'primaryGroupToken', 
'sDRightsEffective', 
'structuralObjectClass', 
'subSchemaSubEntry', 
'tokenGroups', 
'tokenGroupsGlobalAndUniversal', 
'tokenGroupsNoGCAcceptable'
]
```

**Comment by Hackndo** [comment]
Nice job,
Yet it doesn't check all these attributes. If I create a PSO and make it apply to `adm_pixis`, I don't have the `msDS-ResultantPSO` attribute update:

![image](https://github.com/p0dalirius/LDAPmonitor/assets/11051803/62f40962-0dba-4e17-88e3-8d097dc041a3)

Even if this attribute was updated:
![image](https://github.com/p0dalirius/LDAPmonitor/assets/11051803/4339bade-8d78-4abd-afe1-b66459baceea)

I should try and investigate your commit when I have some time

**Comment by Hackndo** [comment]
First, your commit is great, but not used by the rest of the code. `lc.all_ldap_attributes` should be provided to `lc.query()`

```python
_r = lc.query("(objectClass=*)", attributes=lc.all_ldap_attributes)
```

Then, there are some special attributes that, when queried, will return an empty result (trial and error to find these out...)

```python
if entry["lDAPDisplayName"] in ['msDS-ManagedPassword',
                                'msDS-RevealedList',
                                'msds-memberOfTransitive',
                                'msds-memberTransitive',
                                'msds-tokenGroupNames',
                                'msds-tokenGroupNamesGlobalAndUniversal',
                                'msds-tokenGroupNamesNoGCAcceptable',
                                'tokenGroups',
                                'tokenGroupsGlobalAndUniversal',
                                'tokenGroupsNoGCAcceptable']:
   continue
```

I'm not sure why, it's a very strange behavior...

**Edit**:

msDS-ManagedPassword can only be retreived using a secure channel: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/9cd2fc5e-7305-4fb8-b233-2a60bc3eec68

> If the connection is not encrypted, ERROR_DS_CONFIDENTIALITY_REQUIRED is returned.

![image](https://github.com/p0dalirius/LDAPmonitor/assets/11051803/d2ff893c-a243-4fc4-823d-7adc1c25d771)


Other attributes are not to be returned by search operations that are not scoped to a single object (searchFlags set to 0x800 https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/7c1cdf82-1ecc-4834-827e-d26ff95fb207)

![image](https://github.com/p0dalirius/LDAPmonitor/assets/11051803/afb02dd9-3933-4b79-a2b8-63988f012254)
